---
title: "Sss"
author: Ziqi Tang
output:
    html_document

---

# Introduction

New York State’s (NYS) wild turkey population constitutes a significant part of conservation concerns and support for the hunting community within NYS. In the early 1950s, the Department of Conservation  (NYSDEC) helped restore and repopulate NYS wild turkey populations. The NYSDEC had also partnered with the National Wild Turkey Federation and SUNY Environmental Science and Forestry college in 2010 to research the impact of weather patterns and hunting zones on turkey populations. The results of this study have not been published at this time.

The aim of this project is to research, gather and compare data that involves understanding and explaining how land cover, tree canopy cover, elevation and precipitation can affect wild turkey population levels. Within NYS many individuals have noticed seeing less wild turkeys than in years past and changing habitat factors in localized areas may be one factor affecting population levels. By looking at these environmantal variables the aim of this project is to see if areas with less suitable environmental variables correlate to areas of lower population levels. If the results of this study come back to support this hypothesis then there is room for continued research into habitat suitability within NYS for wild turkey populations. 



# Materials and methods

For this project it was important to highlight the key environmental variables that affect wild turkey populations within New York State. The first environmental variable that was used was landcover from the U.S. Geological Survey (USGS). Specifically, the landcover data is a global digital elevation model (DEM) with a horizontal grid spacing of 30 arc seconds (approximately 1 kilometer). The USGS seperated the land cover data into tiles on a world map which can be selected by grid. For this project I was able to select a grid tile that included NY. The next environmental variable that was chosen for this project was Tree canopy cover from the Global Land Analysis & Discovery. The global tree cover data are per pixel estimates of the 2010 percent maximum (peak growing season) tree canopy cover from cloud-free annual growing season composite Landset 7 ETM + data. A median from the annual tree canopy cover cover values from 2009-2011 were used to estimate the 2010 tree cover. Like the Landcover data the tree cover canopy data was chosen from a grid style map with a spatial resoultion of 1 arc-second per pixel, approximately 30 m per pixel. The next environmental variable that was selected was elevation. 


*Elevation-Dr. Williams 

*Precipitation-PRISM 


#Step 1: Loading the required packages 






# Conclusions

[~200 words]

Clear summary adequately describing the results and putting them in context. Discussion of further questions and ways to continue investigation.

# References



